"""added year_formes field to band model

Revision ID: 7b5d2cb7b74f
Revises: 2cb648427872
Create Date: 2024-06-28 23:37:52.384168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b5d2cb7b74f'
down_revision: Union[str, None] = '2cb648427872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('year_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'year_formed')
    # ### end Alembic commands ###
